server:
  port: 8085
  servlet:
    context-path: /dynamic-datasource-example

spring:
  application:
    name: dynamic-datasource-example

datasource:
  oracle:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: SYSTEM
    password: s1rYjtw5Da6uJ+lmeXZ/t/AGqM7cdgLUmzEMv4eudNHhiTgThuOKBmkrG2WIGhwkjy4upfH/FliPzeg7b75hhA==
    initial-size: 5
    max-active: 100
    min-idle: 5
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    max-open-prepared-statements: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 5
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    async-init: true
    useGlobalDataSourceStat: true
    filters: stat,slf4j,config
    filter:
      slf4j:
        enabled: true
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 5000
        merge-sql: true
      config:
        enabled: true
    connect-properties:
      config.decrypt: true
      config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOPapoUinoiqzKf/AhmKD9JNzKcfDZyOgGMwBRgaPUGIlbHtgavnsaBSMT483XfT7v3jymWd/jBI4rUfhgU29wcCAwEAAQ==
    transactionPointcutExpression: (execution(* com.example.multi.datasource.service.*.*(..)) or @annotation(org.springframework.transaction.annotation.Transactional))
  mysql:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8
    username: root
    password: O386MyaJZqoKH9Yd2qOGF33ekGsWls4Odd4YTGZs2mpPFk9ngItzPl7Sf3KVCrYhWOqAyG3FZKx23SAeEXm/jA==
    initial-size: 5
    max-active: 100
    min-idle: 5
    max-wait: 60000
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: -1
    max-open-prepared-statements: 20
    validation-query: select '1'
    validation-query-timeout: 5
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    async-init: true
    useGlobalDataSourceStat: true
    filters: stat,slf4j,config
    filter:
      slf4j:
        enabled: true
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 5000
        merge-sql: true
      config:
        enabled: true
    connect-properties:
      config.decrypt: true
      config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIKSFyctJmct5ewulonvlyWGPOy7qP9WZsgfef5d0U/10lxfAOsYJVcheeJFVxLtdsKq76HWeXU4Gyf2QygLZECAwEAAQ==
    transactionPointcutExpression: (execution(* com.example.multi.datasource.service.*.*(..)) or @annotation(org.springframework.transaction.annotation.Transactional))

logback:
  dir: E:/spring-boot-example/logs/dynamic-datasource-example
  level: INFO
  maxFileSize: 1024MB
  maxHistory: 7